/* One-off generator: reads assets/js/data.js and emits the seed.sql INSERT for site_content.
   Not part of the running site — safe to delete after the first migration. Run: node gen-seed.js */
const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '..', 'assets', 'js', 'data.js');
const src = fs.readFileSync(dataPath, 'utf8');
const jsonText = src
  .replace(/^\/\*[\s\S]*?\*\/\s*/, '')
  .replace(/^window\.MEMORA_SEED\s*=\s*/, '')
  .replace(/;\s*$/, '');
const seed = JSON.parse(jsonText);

delete seed.orders;
if (seed.settings) delete seed.settings.adminPassword;

const json = JSON.stringify(seed);
if (json.indexOf('$seed$') > -1) throw new Error('Seed JSON contains the dollar-quote delimiter — pick a different tag.');

const sql = `-- Generated by supabase/gen-seed.js from assets/js/data.js — do not hand-edit, regenerate instead.
insert into public.site_content (id, data)
values (1, $seed$${json}$seed$::jsonb)
on conflict (id) do update set data = excluded.data, updated_at = now();
`;

fs.writeFileSync(path.join(__dirname, 'seed.sql'), sql);
console.log('Wrote supabase/seed.sql (' + json.length + ' bytes of JSON)');
